// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: homework.proto

package com.umutozd.proto.homeworks;

/**
 * Protobuf type {@code homeworks.AssignHomeworkReq}
 */
public final class AssignHomeworkReq extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:homeworks.AssignHomeworkReq)
    AssignHomeworkReqOrBuilder {
private static final long serialVersionUID = 0L;
  // Use AssignHomeworkReq.newBuilder() to construct.
  private AssignHomeworkReq(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private AssignHomeworkReq() {
    assignTo_ = "";
    questions_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new AssignHomeworkReq();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.umutozd.proto.homeworks.HomeworkProto.internal_static_homeworks_AssignHomeworkReq_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.umutozd.proto.homeworks.HomeworkProto.internal_static_homeworks_AssignHomeworkReq_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.umutozd.proto.homeworks.AssignHomeworkReq.class, com.umutozd.proto.homeworks.AssignHomeworkReq.Builder.class);
  }

  public static final int ASSIGN_TO_FIELD_NUMBER = 1;
  private volatile java.lang.Object assignTo_;
  /**
   * <code>string assign_to = 1;</code>
   * @return The assignTo.
   */
  @java.lang.Override
  public java.lang.String getAssignTo() {
    java.lang.Object ref = assignTo_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      assignTo_ = s;
      return s;
    }
  }
  /**
   * <code>string assign_to = 1;</code>
   * @return The bytes for assignTo.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getAssignToBytes() {
    java.lang.Object ref = assignTo_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      assignTo_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int QUESTIONS_FIELD_NUMBER = 2;
  private java.util.List<com.umutozd.proto.homeworks.Question> questions_;
  /**
   * <code>repeated .homeworks.Question questions = 2;</code>
   */
  @java.lang.Override
  public java.util.List<com.umutozd.proto.homeworks.Question> getQuestionsList() {
    return questions_;
  }
  /**
   * <code>repeated .homeworks.Question questions = 2;</code>
   */
  @java.lang.Override
  public java.util.List<? extends com.umutozd.proto.homeworks.QuestionOrBuilder> 
      getQuestionsOrBuilderList() {
    return questions_;
  }
  /**
   * <code>repeated .homeworks.Question questions = 2;</code>
   */
  @java.lang.Override
  public int getQuestionsCount() {
    return questions_.size();
  }
  /**
   * <code>repeated .homeworks.Question questions = 2;</code>
   */
  @java.lang.Override
  public com.umutozd.proto.homeworks.Question getQuestions(int index) {
    return questions_.get(index);
  }
  /**
   * <code>repeated .homeworks.Question questions = 2;</code>
   */
  @java.lang.Override
  public com.umutozd.proto.homeworks.QuestionOrBuilder getQuestionsOrBuilder(
      int index) {
    return questions_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(assignTo_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, assignTo_);
    }
    for (int i = 0; i < questions_.size(); i++) {
      output.writeMessage(2, questions_.get(i));
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(assignTo_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, assignTo_);
    }
    for (int i = 0; i < questions_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, questions_.get(i));
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.umutozd.proto.homeworks.AssignHomeworkReq)) {
      return super.equals(obj);
    }
    com.umutozd.proto.homeworks.AssignHomeworkReq other = (com.umutozd.proto.homeworks.AssignHomeworkReq) obj;

    if (!getAssignTo()
        .equals(other.getAssignTo())) return false;
    if (!getQuestionsList()
        .equals(other.getQuestionsList())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + ASSIGN_TO_FIELD_NUMBER;
    hash = (53 * hash) + getAssignTo().hashCode();
    if (getQuestionsCount() > 0) {
      hash = (37 * hash) + QUESTIONS_FIELD_NUMBER;
      hash = (53 * hash) + getQuestionsList().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.umutozd.proto.homeworks.AssignHomeworkReq parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.umutozd.proto.homeworks.AssignHomeworkReq parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.umutozd.proto.homeworks.AssignHomeworkReq parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.umutozd.proto.homeworks.AssignHomeworkReq parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.umutozd.proto.homeworks.AssignHomeworkReq parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.umutozd.proto.homeworks.AssignHomeworkReq parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.umutozd.proto.homeworks.AssignHomeworkReq parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.umutozd.proto.homeworks.AssignHomeworkReq parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.umutozd.proto.homeworks.AssignHomeworkReq parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.umutozd.proto.homeworks.AssignHomeworkReq parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.umutozd.proto.homeworks.AssignHomeworkReq parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.umutozd.proto.homeworks.AssignHomeworkReq parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.umutozd.proto.homeworks.AssignHomeworkReq prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code homeworks.AssignHomeworkReq}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:homeworks.AssignHomeworkReq)
      com.umutozd.proto.homeworks.AssignHomeworkReqOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.umutozd.proto.homeworks.HomeworkProto.internal_static_homeworks_AssignHomeworkReq_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.umutozd.proto.homeworks.HomeworkProto.internal_static_homeworks_AssignHomeworkReq_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.umutozd.proto.homeworks.AssignHomeworkReq.class, com.umutozd.proto.homeworks.AssignHomeworkReq.Builder.class);
    }

    // Construct using com.umutozd.proto.homeworks.AssignHomeworkReq.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      assignTo_ = "";

      if (questionsBuilder_ == null) {
        questions_ = java.util.Collections.emptyList();
      } else {
        questions_ = null;
        questionsBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000001);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.umutozd.proto.homeworks.HomeworkProto.internal_static_homeworks_AssignHomeworkReq_descriptor;
    }

    @java.lang.Override
    public com.umutozd.proto.homeworks.AssignHomeworkReq getDefaultInstanceForType() {
      return com.umutozd.proto.homeworks.AssignHomeworkReq.getDefaultInstance();
    }

    @java.lang.Override
    public com.umutozd.proto.homeworks.AssignHomeworkReq build() {
      com.umutozd.proto.homeworks.AssignHomeworkReq result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.umutozd.proto.homeworks.AssignHomeworkReq buildPartial() {
      com.umutozd.proto.homeworks.AssignHomeworkReq result = new com.umutozd.proto.homeworks.AssignHomeworkReq(this);
      int from_bitField0_ = bitField0_;
      result.assignTo_ = assignTo_;
      if (questionsBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          questions_ = java.util.Collections.unmodifiableList(questions_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.questions_ = questions_;
      } else {
        result.questions_ = questionsBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.umutozd.proto.homeworks.AssignHomeworkReq) {
        return mergeFrom((com.umutozd.proto.homeworks.AssignHomeworkReq)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.umutozd.proto.homeworks.AssignHomeworkReq other) {
      if (other == com.umutozd.proto.homeworks.AssignHomeworkReq.getDefaultInstance()) return this;
      if (!other.getAssignTo().isEmpty()) {
        assignTo_ = other.assignTo_;
        onChanged();
      }
      if (questionsBuilder_ == null) {
        if (!other.questions_.isEmpty()) {
          if (questions_.isEmpty()) {
            questions_ = other.questions_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureQuestionsIsMutable();
            questions_.addAll(other.questions_);
          }
          onChanged();
        }
      } else {
        if (!other.questions_.isEmpty()) {
          if (questionsBuilder_.isEmpty()) {
            questionsBuilder_.dispose();
            questionsBuilder_ = null;
            questions_ = other.questions_;
            bitField0_ = (bitField0_ & ~0x00000001);
            questionsBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getQuestionsFieldBuilder() : null;
          } else {
            questionsBuilder_.addAllMessages(other.questions_);
          }
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              assignTo_ = input.readStringRequireUtf8();

              break;
            } // case 10
            case 18: {
              com.umutozd.proto.homeworks.Question m =
                  input.readMessage(
                      com.umutozd.proto.homeworks.Question.parser(),
                      extensionRegistry);
              if (questionsBuilder_ == null) {
                ensureQuestionsIsMutable();
                questions_.add(m);
              } else {
                questionsBuilder_.addMessage(m);
              }
              break;
            } // case 18
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object assignTo_ = "";
    /**
     * <code>string assign_to = 1;</code>
     * @return The assignTo.
     */
    public java.lang.String getAssignTo() {
      java.lang.Object ref = assignTo_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        assignTo_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string assign_to = 1;</code>
     * @return The bytes for assignTo.
     */
    public com.google.protobuf.ByteString
        getAssignToBytes() {
      java.lang.Object ref = assignTo_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        assignTo_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string assign_to = 1;</code>
     * @param value The assignTo to set.
     * @return This builder for chaining.
     */
    public Builder setAssignTo(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      assignTo_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string assign_to = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearAssignTo() {
      
      assignTo_ = getDefaultInstance().getAssignTo();
      onChanged();
      return this;
    }
    /**
     * <code>string assign_to = 1;</code>
     * @param value The bytes for assignTo to set.
     * @return This builder for chaining.
     */
    public Builder setAssignToBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      assignTo_ = value;
      onChanged();
      return this;
    }

    private java.util.List<com.umutozd.proto.homeworks.Question> questions_ =
      java.util.Collections.emptyList();
    private void ensureQuestionsIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        questions_ = new java.util.ArrayList<com.umutozd.proto.homeworks.Question>(questions_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.umutozd.proto.homeworks.Question, com.umutozd.proto.homeworks.Question.Builder, com.umutozd.proto.homeworks.QuestionOrBuilder> questionsBuilder_;

    /**
     * <code>repeated .homeworks.Question questions = 2;</code>
     */
    public java.util.List<com.umutozd.proto.homeworks.Question> getQuestionsList() {
      if (questionsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(questions_);
      } else {
        return questionsBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .homeworks.Question questions = 2;</code>
     */
    public int getQuestionsCount() {
      if (questionsBuilder_ == null) {
        return questions_.size();
      } else {
        return questionsBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .homeworks.Question questions = 2;</code>
     */
    public com.umutozd.proto.homeworks.Question getQuestions(int index) {
      if (questionsBuilder_ == null) {
        return questions_.get(index);
      } else {
        return questionsBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .homeworks.Question questions = 2;</code>
     */
    public Builder setQuestions(
        int index, com.umutozd.proto.homeworks.Question value) {
      if (questionsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureQuestionsIsMutable();
        questions_.set(index, value);
        onChanged();
      } else {
        questionsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .homeworks.Question questions = 2;</code>
     */
    public Builder setQuestions(
        int index, com.umutozd.proto.homeworks.Question.Builder builderForValue) {
      if (questionsBuilder_ == null) {
        ensureQuestionsIsMutable();
        questions_.set(index, builderForValue.build());
        onChanged();
      } else {
        questionsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .homeworks.Question questions = 2;</code>
     */
    public Builder addQuestions(com.umutozd.proto.homeworks.Question value) {
      if (questionsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureQuestionsIsMutable();
        questions_.add(value);
        onChanged();
      } else {
        questionsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .homeworks.Question questions = 2;</code>
     */
    public Builder addQuestions(
        int index, com.umutozd.proto.homeworks.Question value) {
      if (questionsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureQuestionsIsMutable();
        questions_.add(index, value);
        onChanged();
      } else {
        questionsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .homeworks.Question questions = 2;</code>
     */
    public Builder addQuestions(
        com.umutozd.proto.homeworks.Question.Builder builderForValue) {
      if (questionsBuilder_ == null) {
        ensureQuestionsIsMutable();
        questions_.add(builderForValue.build());
        onChanged();
      } else {
        questionsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .homeworks.Question questions = 2;</code>
     */
    public Builder addQuestions(
        int index, com.umutozd.proto.homeworks.Question.Builder builderForValue) {
      if (questionsBuilder_ == null) {
        ensureQuestionsIsMutable();
        questions_.add(index, builderForValue.build());
        onChanged();
      } else {
        questionsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .homeworks.Question questions = 2;</code>
     */
    public Builder addAllQuestions(
        java.lang.Iterable<? extends com.umutozd.proto.homeworks.Question> values) {
      if (questionsBuilder_ == null) {
        ensureQuestionsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, questions_);
        onChanged();
      } else {
        questionsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .homeworks.Question questions = 2;</code>
     */
    public Builder clearQuestions() {
      if (questionsBuilder_ == null) {
        questions_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        questionsBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .homeworks.Question questions = 2;</code>
     */
    public Builder removeQuestions(int index) {
      if (questionsBuilder_ == null) {
        ensureQuestionsIsMutable();
        questions_.remove(index);
        onChanged();
      } else {
        questionsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .homeworks.Question questions = 2;</code>
     */
    public com.umutozd.proto.homeworks.Question.Builder getQuestionsBuilder(
        int index) {
      return getQuestionsFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .homeworks.Question questions = 2;</code>
     */
    public com.umutozd.proto.homeworks.QuestionOrBuilder getQuestionsOrBuilder(
        int index) {
      if (questionsBuilder_ == null) {
        return questions_.get(index);  } else {
        return questionsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .homeworks.Question questions = 2;</code>
     */
    public java.util.List<? extends com.umutozd.proto.homeworks.QuestionOrBuilder> 
         getQuestionsOrBuilderList() {
      if (questionsBuilder_ != null) {
        return questionsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(questions_);
      }
    }
    /**
     * <code>repeated .homeworks.Question questions = 2;</code>
     */
    public com.umutozd.proto.homeworks.Question.Builder addQuestionsBuilder() {
      return getQuestionsFieldBuilder().addBuilder(
          com.umutozd.proto.homeworks.Question.getDefaultInstance());
    }
    /**
     * <code>repeated .homeworks.Question questions = 2;</code>
     */
    public com.umutozd.proto.homeworks.Question.Builder addQuestionsBuilder(
        int index) {
      return getQuestionsFieldBuilder().addBuilder(
          index, com.umutozd.proto.homeworks.Question.getDefaultInstance());
    }
    /**
     * <code>repeated .homeworks.Question questions = 2;</code>
     */
    public java.util.List<com.umutozd.proto.homeworks.Question.Builder> 
         getQuestionsBuilderList() {
      return getQuestionsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.umutozd.proto.homeworks.Question, com.umutozd.proto.homeworks.Question.Builder, com.umutozd.proto.homeworks.QuestionOrBuilder> 
        getQuestionsFieldBuilder() {
      if (questionsBuilder_ == null) {
        questionsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.umutozd.proto.homeworks.Question, com.umutozd.proto.homeworks.Question.Builder, com.umutozd.proto.homeworks.QuestionOrBuilder>(
                questions_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        questions_ = null;
      }
      return questionsBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:homeworks.AssignHomeworkReq)
  }

  // @@protoc_insertion_point(class_scope:homeworks.AssignHomeworkReq)
  private static final com.umutozd.proto.homeworks.AssignHomeworkReq DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.umutozd.proto.homeworks.AssignHomeworkReq();
  }

  public static com.umutozd.proto.homeworks.AssignHomeworkReq getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<AssignHomeworkReq>
      PARSER = new com.google.protobuf.AbstractParser<AssignHomeworkReq>() {
    @java.lang.Override
    public AssignHomeworkReq parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<AssignHomeworkReq> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<AssignHomeworkReq> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.umutozd.proto.homeworks.AssignHomeworkReq getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

