// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: user.proto

package com.umutozd.proto.homeworks;

public interface CreateUserReqOrBuilder extends
    // @@protoc_insertion_point(interface_extends:homeworks.CreateUserReq)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string email = 1;</code>
   * @return The email.
   */
  java.lang.String getEmail();
  /**
   * <code>string email = 1;</code>
   * @return The bytes for email.
   */
  com.google.protobuf.ByteString
      getEmailBytes();

  /**
   * <code>string name = 2;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>string name = 2;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();
}
