// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: user.proto

package com.umutozd.proto.homeworks;

public interface GetUserReqOrBuilder extends
    // @@protoc_insertion_point(interface_extends:homeworks.GetUserReq)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string id = 1;</code>
   * @return The id.
   */
  java.lang.String getId();
  /**
   * <code>string id = 1;</code>
   * @return The bytes for id.
   */
  com.google.protobuf.ByteString
      getIdBytes();

  /**
   * <code>string email = 2;</code>
   * @return The email.
   */
  java.lang.String getEmail();
  /**
   * <code>string email = 2;</code>
   * @return The bytes for email.
   */
  com.google.protobuf.ByteString
      getEmailBytes();
}
