// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: homework.proto

package com.umutozd.proto.homeworks;

public interface HomeworkOrBuilder extends
    // @@protoc_insertion_point(interface_extends:homeworks.Homework)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * The unique id of this Homework
   * </pre>
   *
   * <code>string id = 1;</code>
   * @return The id.
   */
  java.lang.String getId();
  /**
   * <pre>
   * The unique id of this Homework
   * </pre>
   *
   * <code>string id = 1;</code>
   * @return The bytes for id.
   */
  com.google.protobuf.ByteString
      getIdBytes();

  /**
   * <pre>
   * The id of the user that this Homework is assigned to. Cannot be empty.
   * </pre>
   *
   * <code>string assigned_to = 2;</code>
   * @return The assignedTo.
   */
  java.lang.String getAssignedTo();
  /**
   * <pre>
   * The id of the user that this Homework is assigned to. Cannot be empty.
   * </pre>
   *
   * <code>string assigned_to = 2;</code>
   * @return The bytes for assignedTo.
   */
  com.google.protobuf.ByteString
      getAssignedToBytes();

  /**
   * <code>repeated .homeworks.Question questions = 3;</code>
   */
  java.util.List<com.umutozd.proto.homeworks.Question> 
      getQuestionsList();
  /**
   * <code>repeated .homeworks.Question questions = 3;</code>
   */
  com.umutozd.proto.homeworks.Question getQuestions(int index);
  /**
   * <code>repeated .homeworks.Question questions = 3;</code>
   */
  int getQuestionsCount();
  /**
   * <code>repeated .homeworks.Question questions = 3;</code>
   */
  java.util.List<? extends com.umutozd.proto.homeworks.QuestionOrBuilder> 
      getQuestionsOrBuilderList();
  /**
   * <code>repeated .homeworks.Question questions = 3;</code>
   */
  com.umutozd.proto.homeworks.QuestionOrBuilder getQuestionsOrBuilder(
      int index);

  /**
   * <code>repeated .homeworks.Answer answers = 4;</code>
   */
  java.util.List<com.umutozd.proto.homeworks.Answer> 
      getAnswersList();
  /**
   * <code>repeated .homeworks.Answer answers = 4;</code>
   */
  com.umutozd.proto.homeworks.Answer getAnswers(int index);
  /**
   * <code>repeated .homeworks.Answer answers = 4;</code>
   */
  int getAnswersCount();
  /**
   * <code>repeated .homeworks.Answer answers = 4;</code>
   */
  java.util.List<? extends com.umutozd.proto.homeworks.AnswerOrBuilder> 
      getAnswersOrBuilderList();
  /**
   * <code>repeated .homeworks.Answer answers = 4;</code>
   */
  com.umutozd.proto.homeworks.AnswerOrBuilder getAnswersOrBuilder(
      int index);

  /**
   * <code>bool completed = 5;</code>
   * @return The completed.
   */
  boolean getCompleted();
}
