// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: homework.proto

package com.umutozd.proto.homeworks;

public final class HomeworkProto {
  private HomeworkProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_homeworks_Homework_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_homeworks_Homework_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_homeworks_Question_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_homeworks_Question_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_homeworks_Answer_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_homeworks_Answer_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_homeworks_AssignHomeworkReq_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_homeworks_AssignHomeworkReq_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_homeworks_DoHomeworkReq_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_homeworks_DoHomeworkReq_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_homeworks_UserAndHomework_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_homeworks_UserAndHomework_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016homework.proto\022\thomeworks\032\nuser.proto\"" +
      "\212\001\n\010Homework\022\n\n\002id\030\001 \001(\t\022\023\n\013assigned_to\030" +
      "\002 \001(\t\022&\n\tquestions\030\003 \003(\0132\023.homeworks.Que" +
      "stion\022\"\n\007answers\030\004 \003(\0132\021.homeworks.Answe" +
      "r\022\021\n\tcompleted\030\005 \001(\010\"\030\n\010Question\022\014\n\004text" +
      "\030\001 \001(\t\"\026\n\006Answer\022\014\n\004text\030\002 \001(\t\"N\n\021Assign" +
      "HomeworkReq\022\021\n\tassign_to\030\001 \001(\t\022&\n\tquesti" +
      "ons\030\002 \003(\0132\023.homeworks.Question\"l\n\rDoHome" +
      "workReq\022\023\n\013homework_id\030\001 \001(\t\022\017\n\007user_id\030" +
      "\002 \001(\t\022\"\n\007answers\030\003 \003(\0132\021.homeworks.Answe" +
      "r\022\021\n\tcompleted\030\004 \001(\010\"W\n\017UserAndHomework\022" +
      "\035\n\004user\030\001 \001(\0132\017.homeworks.User\022%\n\010homewo" +
      "rk\030\002 \001(\0132\023.homeworks.Homework2\223\001\n\017Homewo" +
      "rkService\022C\n\016AssignHomework\022\034.homeworks." +
      "AssignHomeworkReq\032\023.homeworks.Homework\022;" +
      "\n\nDoHomework\022\030.homeworks.DoHomeworkReq\032\023" +
      ".homeworks.HomeworkB.\n\033com.umutozd.proto" +
      ".homeworksB\rHomeworkProtoP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.umutozd.proto.homeworks.UserProto.getDescriptor(),
        });
    internal_static_homeworks_Homework_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_homeworks_Homework_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_homeworks_Homework_descriptor,
        new java.lang.String[] { "Id", "AssignedTo", "Questions", "Answers", "Completed", });
    internal_static_homeworks_Question_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_homeworks_Question_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_homeworks_Question_descriptor,
        new java.lang.String[] { "Text", });
    internal_static_homeworks_Answer_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_homeworks_Answer_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_homeworks_Answer_descriptor,
        new java.lang.String[] { "Text", });
    internal_static_homeworks_AssignHomeworkReq_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_homeworks_AssignHomeworkReq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_homeworks_AssignHomeworkReq_descriptor,
        new java.lang.String[] { "AssignTo", "Questions", });
    internal_static_homeworks_DoHomeworkReq_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_homeworks_DoHomeworkReq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_homeworks_DoHomeworkReq_descriptor,
        new java.lang.String[] { "HomeworkId", "UserId", "Answers", "Completed", });
    internal_static_homeworks_UserAndHomework_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_homeworks_UserAndHomework_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_homeworks_UserAndHomework_descriptor,
        new java.lang.String[] { "User", "Homework", });
    com.umutozd.proto.homeworks.UserProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
