// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: homework.proto

package com.umutozd.proto.homeworks;

public interface UserAndHomeworkOrBuilder extends
    // @@protoc_insertion_point(interface_extends:homeworks.UserAndHomework)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.homeworks.User user = 1;</code>
   * @return Whether the user field is set.
   */
  boolean hasUser();
  /**
   * <code>.homeworks.User user = 1;</code>
   * @return The user.
   */
  com.umutozd.proto.homeworks.User getUser();
  /**
   * <code>.homeworks.User user = 1;</code>
   */
  com.umutozd.proto.homeworks.UserOrBuilder getUserOrBuilder();

  /**
   * <code>.homeworks.Homework homework = 2;</code>
   * @return Whether the homework field is set.
   */
  boolean hasHomework();
  /**
   * <code>.homeworks.Homework homework = 2;</code>
   * @return The homework.
   */
  com.umutozd.proto.homeworks.Homework getHomework();
  /**
   * <code>.homeworks.Homework homework = 2;</code>
   */
  com.umutozd.proto.homeworks.HomeworkOrBuilder getHomeworkOrBuilder();
}
