// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: homework.proto

package com.umutozd.proto.homeworks;

/**
 * Protobuf type {@code homeworks.UserAndHomework}
 */
public final class UserAndHomework extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:homeworks.UserAndHomework)
    UserAndHomeworkOrBuilder {
private static final long serialVersionUID = 0L;
  // Use UserAndHomework.newBuilder() to construct.
  private UserAndHomework(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private UserAndHomework() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new UserAndHomework();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.umutozd.proto.homeworks.HomeworkProto.internal_static_homeworks_UserAndHomework_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.umutozd.proto.homeworks.HomeworkProto.internal_static_homeworks_UserAndHomework_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.umutozd.proto.homeworks.UserAndHomework.class, com.umutozd.proto.homeworks.UserAndHomework.Builder.class);
  }

  public static final int USER_FIELD_NUMBER = 1;
  private com.umutozd.proto.homeworks.User user_;
  /**
   * <code>.homeworks.User user = 1;</code>
   * @return Whether the user field is set.
   */
  @java.lang.Override
  public boolean hasUser() {
    return user_ != null;
  }
  /**
   * <code>.homeworks.User user = 1;</code>
   * @return The user.
   */
  @java.lang.Override
  public com.umutozd.proto.homeworks.User getUser() {
    return user_ == null ? com.umutozd.proto.homeworks.User.getDefaultInstance() : user_;
  }
  /**
   * <code>.homeworks.User user = 1;</code>
   */
  @java.lang.Override
  public com.umutozd.proto.homeworks.UserOrBuilder getUserOrBuilder() {
    return getUser();
  }

  public static final int HOMEWORK_FIELD_NUMBER = 2;
  private com.umutozd.proto.homeworks.Homework homework_;
  /**
   * <code>.homeworks.Homework homework = 2;</code>
   * @return Whether the homework field is set.
   */
  @java.lang.Override
  public boolean hasHomework() {
    return homework_ != null;
  }
  /**
   * <code>.homeworks.Homework homework = 2;</code>
   * @return The homework.
   */
  @java.lang.Override
  public com.umutozd.proto.homeworks.Homework getHomework() {
    return homework_ == null ? com.umutozd.proto.homeworks.Homework.getDefaultInstance() : homework_;
  }
  /**
   * <code>.homeworks.Homework homework = 2;</code>
   */
  @java.lang.Override
  public com.umutozd.proto.homeworks.HomeworkOrBuilder getHomeworkOrBuilder() {
    return getHomework();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (user_ != null) {
      output.writeMessage(1, getUser());
    }
    if (homework_ != null) {
      output.writeMessage(2, getHomework());
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (user_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getUser());
    }
    if (homework_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getHomework());
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.umutozd.proto.homeworks.UserAndHomework)) {
      return super.equals(obj);
    }
    com.umutozd.proto.homeworks.UserAndHomework other = (com.umutozd.proto.homeworks.UserAndHomework) obj;

    if (hasUser() != other.hasUser()) return false;
    if (hasUser()) {
      if (!getUser()
          .equals(other.getUser())) return false;
    }
    if (hasHomework() != other.hasHomework()) return false;
    if (hasHomework()) {
      if (!getHomework()
          .equals(other.getHomework())) return false;
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasUser()) {
      hash = (37 * hash) + USER_FIELD_NUMBER;
      hash = (53 * hash) + getUser().hashCode();
    }
    if (hasHomework()) {
      hash = (37 * hash) + HOMEWORK_FIELD_NUMBER;
      hash = (53 * hash) + getHomework().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.umutozd.proto.homeworks.UserAndHomework parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.umutozd.proto.homeworks.UserAndHomework parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.umutozd.proto.homeworks.UserAndHomework parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.umutozd.proto.homeworks.UserAndHomework parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.umutozd.proto.homeworks.UserAndHomework parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.umutozd.proto.homeworks.UserAndHomework parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.umutozd.proto.homeworks.UserAndHomework parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.umutozd.proto.homeworks.UserAndHomework parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.umutozd.proto.homeworks.UserAndHomework parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.umutozd.proto.homeworks.UserAndHomework parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.umutozd.proto.homeworks.UserAndHomework parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.umutozd.proto.homeworks.UserAndHomework parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.umutozd.proto.homeworks.UserAndHomework prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code homeworks.UserAndHomework}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:homeworks.UserAndHomework)
      com.umutozd.proto.homeworks.UserAndHomeworkOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.umutozd.proto.homeworks.HomeworkProto.internal_static_homeworks_UserAndHomework_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.umutozd.proto.homeworks.HomeworkProto.internal_static_homeworks_UserAndHomework_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.umutozd.proto.homeworks.UserAndHomework.class, com.umutozd.proto.homeworks.UserAndHomework.Builder.class);
    }

    // Construct using com.umutozd.proto.homeworks.UserAndHomework.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (userBuilder_ == null) {
        user_ = null;
      } else {
        user_ = null;
        userBuilder_ = null;
      }
      if (homeworkBuilder_ == null) {
        homework_ = null;
      } else {
        homework_ = null;
        homeworkBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.umutozd.proto.homeworks.HomeworkProto.internal_static_homeworks_UserAndHomework_descriptor;
    }

    @java.lang.Override
    public com.umutozd.proto.homeworks.UserAndHomework getDefaultInstanceForType() {
      return com.umutozd.proto.homeworks.UserAndHomework.getDefaultInstance();
    }

    @java.lang.Override
    public com.umutozd.proto.homeworks.UserAndHomework build() {
      com.umutozd.proto.homeworks.UserAndHomework result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.umutozd.proto.homeworks.UserAndHomework buildPartial() {
      com.umutozd.proto.homeworks.UserAndHomework result = new com.umutozd.proto.homeworks.UserAndHomework(this);
      if (userBuilder_ == null) {
        result.user_ = user_;
      } else {
        result.user_ = userBuilder_.build();
      }
      if (homeworkBuilder_ == null) {
        result.homework_ = homework_;
      } else {
        result.homework_ = homeworkBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.umutozd.proto.homeworks.UserAndHomework) {
        return mergeFrom((com.umutozd.proto.homeworks.UserAndHomework)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.umutozd.proto.homeworks.UserAndHomework other) {
      if (other == com.umutozd.proto.homeworks.UserAndHomework.getDefaultInstance()) return this;
      if (other.hasUser()) {
        mergeUser(other.getUser());
      }
      if (other.hasHomework()) {
        mergeHomework(other.getHomework());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              input.readMessage(
                  getUserFieldBuilder().getBuilder(),
                  extensionRegistry);

              break;
            } // case 10
            case 18: {
              input.readMessage(
                  getHomeworkFieldBuilder().getBuilder(),
                  extensionRegistry);

              break;
            } // case 18
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }

    private com.umutozd.proto.homeworks.User user_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.umutozd.proto.homeworks.User, com.umutozd.proto.homeworks.User.Builder, com.umutozd.proto.homeworks.UserOrBuilder> userBuilder_;
    /**
     * <code>.homeworks.User user = 1;</code>
     * @return Whether the user field is set.
     */
    public boolean hasUser() {
      return userBuilder_ != null || user_ != null;
    }
    /**
     * <code>.homeworks.User user = 1;</code>
     * @return The user.
     */
    public com.umutozd.proto.homeworks.User getUser() {
      if (userBuilder_ == null) {
        return user_ == null ? com.umutozd.proto.homeworks.User.getDefaultInstance() : user_;
      } else {
        return userBuilder_.getMessage();
      }
    }
    /**
     * <code>.homeworks.User user = 1;</code>
     */
    public Builder setUser(com.umutozd.proto.homeworks.User value) {
      if (userBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        user_ = value;
        onChanged();
      } else {
        userBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.homeworks.User user = 1;</code>
     */
    public Builder setUser(
        com.umutozd.proto.homeworks.User.Builder builderForValue) {
      if (userBuilder_ == null) {
        user_ = builderForValue.build();
        onChanged();
      } else {
        userBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.homeworks.User user = 1;</code>
     */
    public Builder mergeUser(com.umutozd.proto.homeworks.User value) {
      if (userBuilder_ == null) {
        if (user_ != null) {
          user_ =
            com.umutozd.proto.homeworks.User.newBuilder(user_).mergeFrom(value).buildPartial();
        } else {
          user_ = value;
        }
        onChanged();
      } else {
        userBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.homeworks.User user = 1;</code>
     */
    public Builder clearUser() {
      if (userBuilder_ == null) {
        user_ = null;
        onChanged();
      } else {
        user_ = null;
        userBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.homeworks.User user = 1;</code>
     */
    public com.umutozd.proto.homeworks.User.Builder getUserBuilder() {
      
      onChanged();
      return getUserFieldBuilder().getBuilder();
    }
    /**
     * <code>.homeworks.User user = 1;</code>
     */
    public com.umutozd.proto.homeworks.UserOrBuilder getUserOrBuilder() {
      if (userBuilder_ != null) {
        return userBuilder_.getMessageOrBuilder();
      } else {
        return user_ == null ?
            com.umutozd.proto.homeworks.User.getDefaultInstance() : user_;
      }
    }
    /**
     * <code>.homeworks.User user = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.umutozd.proto.homeworks.User, com.umutozd.proto.homeworks.User.Builder, com.umutozd.proto.homeworks.UserOrBuilder> 
        getUserFieldBuilder() {
      if (userBuilder_ == null) {
        userBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.umutozd.proto.homeworks.User, com.umutozd.proto.homeworks.User.Builder, com.umutozd.proto.homeworks.UserOrBuilder>(
                getUser(),
                getParentForChildren(),
                isClean());
        user_ = null;
      }
      return userBuilder_;
    }

    private com.umutozd.proto.homeworks.Homework homework_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.umutozd.proto.homeworks.Homework, com.umutozd.proto.homeworks.Homework.Builder, com.umutozd.proto.homeworks.HomeworkOrBuilder> homeworkBuilder_;
    /**
     * <code>.homeworks.Homework homework = 2;</code>
     * @return Whether the homework field is set.
     */
    public boolean hasHomework() {
      return homeworkBuilder_ != null || homework_ != null;
    }
    /**
     * <code>.homeworks.Homework homework = 2;</code>
     * @return The homework.
     */
    public com.umutozd.proto.homeworks.Homework getHomework() {
      if (homeworkBuilder_ == null) {
        return homework_ == null ? com.umutozd.proto.homeworks.Homework.getDefaultInstance() : homework_;
      } else {
        return homeworkBuilder_.getMessage();
      }
    }
    /**
     * <code>.homeworks.Homework homework = 2;</code>
     */
    public Builder setHomework(com.umutozd.proto.homeworks.Homework value) {
      if (homeworkBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        homework_ = value;
        onChanged();
      } else {
        homeworkBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.homeworks.Homework homework = 2;</code>
     */
    public Builder setHomework(
        com.umutozd.proto.homeworks.Homework.Builder builderForValue) {
      if (homeworkBuilder_ == null) {
        homework_ = builderForValue.build();
        onChanged();
      } else {
        homeworkBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.homeworks.Homework homework = 2;</code>
     */
    public Builder mergeHomework(com.umutozd.proto.homeworks.Homework value) {
      if (homeworkBuilder_ == null) {
        if (homework_ != null) {
          homework_ =
            com.umutozd.proto.homeworks.Homework.newBuilder(homework_).mergeFrom(value).buildPartial();
        } else {
          homework_ = value;
        }
        onChanged();
      } else {
        homeworkBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.homeworks.Homework homework = 2;</code>
     */
    public Builder clearHomework() {
      if (homeworkBuilder_ == null) {
        homework_ = null;
        onChanged();
      } else {
        homework_ = null;
        homeworkBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.homeworks.Homework homework = 2;</code>
     */
    public com.umutozd.proto.homeworks.Homework.Builder getHomeworkBuilder() {
      
      onChanged();
      return getHomeworkFieldBuilder().getBuilder();
    }
    /**
     * <code>.homeworks.Homework homework = 2;</code>
     */
    public com.umutozd.proto.homeworks.HomeworkOrBuilder getHomeworkOrBuilder() {
      if (homeworkBuilder_ != null) {
        return homeworkBuilder_.getMessageOrBuilder();
      } else {
        return homework_ == null ?
            com.umutozd.proto.homeworks.Homework.getDefaultInstance() : homework_;
      }
    }
    /**
     * <code>.homeworks.Homework homework = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.umutozd.proto.homeworks.Homework, com.umutozd.proto.homeworks.Homework.Builder, com.umutozd.proto.homeworks.HomeworkOrBuilder> 
        getHomeworkFieldBuilder() {
      if (homeworkBuilder_ == null) {
        homeworkBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.umutozd.proto.homeworks.Homework, com.umutozd.proto.homeworks.Homework.Builder, com.umutozd.proto.homeworks.HomeworkOrBuilder>(
                getHomework(),
                getParentForChildren(),
                isClean());
        homework_ = null;
      }
      return homeworkBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:homeworks.UserAndHomework)
  }

  // @@protoc_insertion_point(class_scope:homeworks.UserAndHomework)
  private static final com.umutozd.proto.homeworks.UserAndHomework DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.umutozd.proto.homeworks.UserAndHomework();
  }

  public static com.umutozd.proto.homeworks.UserAndHomework getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<UserAndHomework>
      PARSER = new com.google.protobuf.AbstractParser<UserAndHomework>() {
    @java.lang.Override
    public UserAndHomework parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<UserAndHomework> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<UserAndHomework> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.umutozd.proto.homeworks.UserAndHomework getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

