// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: user.proto

package com.umutozd.proto.homeworks;

public final class UserProto {
  private UserProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_homeworks_User_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_homeworks_User_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_homeworks_CreateUserReq_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_homeworks_CreateUserReq_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_homeworks_GetUserReq_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_homeworks_GetUserReq_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\nuser.proto\022\thomeworks\"/\n\004User\022\n\n\002id\030\001 " +
      "\001(\t\022\r\n\005email\030\002 \001(\t\022\014\n\004name\030\003 \001(\t\",\n\rCrea" +
      "teUserReq\022\r\n\005email\030\001 \001(\t\022\014\n\004name\030\002 \001(\t\"\'" +
      "\n\nGetUserReq\022\n\n\002id\030\001 \001(\t\022\r\n\005email\030\002 \001(\t2" +
      "z\n\014UsersService\0227\n\nCreateUser\022\030.homework" +
      "s.CreateUserReq\032\017.homeworks.User\0221\n\007GetU" +
      "ser\022\025.homeworks.GetUserReq\032\017.homeworks.U" +
      "serB*\n\033com.umutozd.proto.homeworksB\tUser" +
      "ProtoP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_homeworks_User_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_homeworks_User_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_homeworks_User_descriptor,
        new java.lang.String[] { "Id", "Email", "Name", });
    internal_static_homeworks_CreateUserReq_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_homeworks_CreateUserReq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_homeworks_CreateUserReq_descriptor,
        new java.lang.String[] { "Email", "Name", });
    internal_static_homeworks_GetUserReq_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_homeworks_GetUserReq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_homeworks_GetUserReq_descriptor,
        new java.lang.String[] { "Id", "Email", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
