// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: homework.proto

package proto.homeworks;

public interface AnswerOrBuilder extends
    // @@protoc_insertion_point(interface_extends:homeworks.Answer)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string text = 2;</code>
   * @return The text.
   */
  java.lang.String getText();
  /**
   * <code>string text = 2;</code>
   * @return The bytes for text.
   */
  com.google.protobuf.ByteString
      getTextBytes();
}
