// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: homework.proto

package proto.homeworks;

/**
 * Protobuf type {@code homeworks.DoHomeworkReq}
 */
public final class DoHomeworkReq extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:homeworks.DoHomeworkReq)
    DoHomeworkReqOrBuilder {
private static final long serialVersionUID = 0L;
  // Use DoHomeworkReq.newBuilder() to construct.
  private DoHomeworkReq(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private DoHomeworkReq() {
    homeworkId_ = "";
    userId_ = "";
    answers_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new DoHomeworkReq();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return proto.homeworks.HomeworkProto.internal_static_homeworks_DoHomeworkReq_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return proto.homeworks.HomeworkProto.internal_static_homeworks_DoHomeworkReq_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            proto.homeworks.DoHomeworkReq.class, proto.homeworks.DoHomeworkReq.Builder.class);
  }

  public static final int HOMEWORK_ID_FIELD_NUMBER = 1;
  private volatile java.lang.Object homeworkId_;
  /**
   * <pre>
   * The id of the Homework to be done
   * </pre>
   *
   * <code>string homework_id = 1;</code>
   * @return The homeworkId.
   */
  @java.lang.Override
  public java.lang.String getHomeworkId() {
    java.lang.Object ref = homeworkId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      homeworkId_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * The id of the Homework to be done
   * </pre>
   *
   * <code>string homework_id = 1;</code>
   * @return The bytes for homeworkId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getHomeworkIdBytes() {
    java.lang.Object ref = homeworkId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      homeworkId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int USER_ID_FIELD_NUMBER = 2;
  private volatile java.lang.Object userId_;
  /**
   * <pre>
   * The id of the User that does the Homework
   * </pre>
   *
   * <code>string user_id = 2;</code>
   * @return The userId.
   */
  @java.lang.Override
  public java.lang.String getUserId() {
    java.lang.Object ref = userId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      userId_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * The id of the User that does the Homework
   * </pre>
   *
   * <code>string user_id = 2;</code>
   * @return The bytes for userId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getUserIdBytes() {
    java.lang.Object ref = userId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      userId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ANSWERS_FIELD_NUMBER = 3;
  private java.util.List<proto.homeworks.Answer> answers_;
  /**
   * <pre>
   * All the answers to the Homework. The number of answers must be equal to the
   * number of questions. Answer texts may be empty.
   * </pre>
   *
   * <code>repeated .homeworks.Answer answers = 3;</code>
   */
  @java.lang.Override
  public java.util.List<proto.homeworks.Answer> getAnswersList() {
    return answers_;
  }
  /**
   * <pre>
   * All the answers to the Homework. The number of answers must be equal to the
   * number of questions. Answer texts may be empty.
   * </pre>
   *
   * <code>repeated .homeworks.Answer answers = 3;</code>
   */
  @java.lang.Override
  public java.util.List<? extends proto.homeworks.AnswerOrBuilder> 
      getAnswersOrBuilderList() {
    return answers_;
  }
  /**
   * <pre>
   * All the answers to the Homework. The number of answers must be equal to the
   * number of questions. Answer texts may be empty.
   * </pre>
   *
   * <code>repeated .homeworks.Answer answers = 3;</code>
   */
  @java.lang.Override
  public int getAnswersCount() {
    return answers_.size();
  }
  /**
   * <pre>
   * All the answers to the Homework. The number of answers must be equal to the
   * number of questions. Answer texts may be empty.
   * </pre>
   *
   * <code>repeated .homeworks.Answer answers = 3;</code>
   */
  @java.lang.Override
  public proto.homeworks.Answer getAnswers(int index) {
    return answers_.get(index);
  }
  /**
   * <pre>
   * All the answers to the Homework. The number of answers must be equal to the
   * number of questions. Answer texts may be empty.
   * </pre>
   *
   * <code>repeated .homeworks.Answer answers = 3;</code>
   */
  @java.lang.Override
  public proto.homeworks.AnswerOrBuilder getAnswersOrBuilder(
      int index) {
    return answers_.get(index);
  }

  public static final int COMPLETED_FIELD_NUMBER = 4;
  private boolean completed_;
  /**
   * <pre>
   * Whether this Homework is completed or not
   * </pre>
   *
   * <code>bool completed = 4;</code>
   * @return The completed.
   */
  @java.lang.Override
  public boolean getCompleted() {
    return completed_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(homeworkId_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, homeworkId_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(userId_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, userId_);
    }
    for (int i = 0; i < answers_.size(); i++) {
      output.writeMessage(3, answers_.get(i));
    }
    if (completed_ != false) {
      output.writeBool(4, completed_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(homeworkId_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, homeworkId_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(userId_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, userId_);
    }
    for (int i = 0; i < answers_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, answers_.get(i));
    }
    if (completed_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(4, completed_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof proto.homeworks.DoHomeworkReq)) {
      return super.equals(obj);
    }
    proto.homeworks.DoHomeworkReq other = (proto.homeworks.DoHomeworkReq) obj;

    if (!getHomeworkId()
        .equals(other.getHomeworkId())) return false;
    if (!getUserId()
        .equals(other.getUserId())) return false;
    if (!getAnswersList()
        .equals(other.getAnswersList())) return false;
    if (getCompleted()
        != other.getCompleted()) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + HOMEWORK_ID_FIELD_NUMBER;
    hash = (53 * hash) + getHomeworkId().hashCode();
    hash = (37 * hash) + USER_ID_FIELD_NUMBER;
    hash = (53 * hash) + getUserId().hashCode();
    if (getAnswersCount() > 0) {
      hash = (37 * hash) + ANSWERS_FIELD_NUMBER;
      hash = (53 * hash) + getAnswersList().hashCode();
    }
    hash = (37 * hash) + COMPLETED_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getCompleted());
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static proto.homeworks.DoHomeworkReq parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static proto.homeworks.DoHomeworkReq parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static proto.homeworks.DoHomeworkReq parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static proto.homeworks.DoHomeworkReq parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static proto.homeworks.DoHomeworkReq parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static proto.homeworks.DoHomeworkReq parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static proto.homeworks.DoHomeworkReq parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static proto.homeworks.DoHomeworkReq parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static proto.homeworks.DoHomeworkReq parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static proto.homeworks.DoHomeworkReq parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static proto.homeworks.DoHomeworkReq parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static proto.homeworks.DoHomeworkReq parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(proto.homeworks.DoHomeworkReq prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code homeworks.DoHomeworkReq}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:homeworks.DoHomeworkReq)
      proto.homeworks.DoHomeworkReqOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return proto.homeworks.HomeworkProto.internal_static_homeworks_DoHomeworkReq_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return proto.homeworks.HomeworkProto.internal_static_homeworks_DoHomeworkReq_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              proto.homeworks.DoHomeworkReq.class, proto.homeworks.DoHomeworkReq.Builder.class);
    }

    // Construct using proto.homeworks.DoHomeworkReq.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      homeworkId_ = "";

      userId_ = "";

      if (answersBuilder_ == null) {
        answers_ = java.util.Collections.emptyList();
      } else {
        answers_ = null;
        answersBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000001);
      completed_ = false;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return proto.homeworks.HomeworkProto.internal_static_homeworks_DoHomeworkReq_descriptor;
    }

    @java.lang.Override
    public proto.homeworks.DoHomeworkReq getDefaultInstanceForType() {
      return proto.homeworks.DoHomeworkReq.getDefaultInstance();
    }

    @java.lang.Override
    public proto.homeworks.DoHomeworkReq build() {
      proto.homeworks.DoHomeworkReq result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public proto.homeworks.DoHomeworkReq buildPartial() {
      proto.homeworks.DoHomeworkReq result = new proto.homeworks.DoHomeworkReq(this);
      int from_bitField0_ = bitField0_;
      result.homeworkId_ = homeworkId_;
      result.userId_ = userId_;
      if (answersBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          answers_ = java.util.Collections.unmodifiableList(answers_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.answers_ = answers_;
      } else {
        result.answers_ = answersBuilder_.build();
      }
      result.completed_ = completed_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof proto.homeworks.DoHomeworkReq) {
        return mergeFrom((proto.homeworks.DoHomeworkReq)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(proto.homeworks.DoHomeworkReq other) {
      if (other == proto.homeworks.DoHomeworkReq.getDefaultInstance()) return this;
      if (!other.getHomeworkId().isEmpty()) {
        homeworkId_ = other.homeworkId_;
        onChanged();
      }
      if (!other.getUserId().isEmpty()) {
        userId_ = other.userId_;
        onChanged();
      }
      if (answersBuilder_ == null) {
        if (!other.answers_.isEmpty()) {
          if (answers_.isEmpty()) {
            answers_ = other.answers_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureAnswersIsMutable();
            answers_.addAll(other.answers_);
          }
          onChanged();
        }
      } else {
        if (!other.answers_.isEmpty()) {
          if (answersBuilder_.isEmpty()) {
            answersBuilder_.dispose();
            answersBuilder_ = null;
            answers_ = other.answers_;
            bitField0_ = (bitField0_ & ~0x00000001);
            answersBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getAnswersFieldBuilder() : null;
          } else {
            answersBuilder_.addAllMessages(other.answers_);
          }
        }
      }
      if (other.getCompleted() != false) {
        setCompleted(other.getCompleted());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              homeworkId_ = input.readStringRequireUtf8();

              break;
            } // case 10
            case 18: {
              userId_ = input.readStringRequireUtf8();

              break;
            } // case 18
            case 26: {
              proto.homeworks.Answer m =
                  input.readMessage(
                      proto.homeworks.Answer.parser(),
                      extensionRegistry);
              if (answersBuilder_ == null) {
                ensureAnswersIsMutable();
                answers_.add(m);
              } else {
                answersBuilder_.addMessage(m);
              }
              break;
            } // case 26
            case 32: {
              completed_ = input.readBool();

              break;
            } // case 32
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object homeworkId_ = "";
    /**
     * <pre>
     * The id of the Homework to be done
     * </pre>
     *
     * <code>string homework_id = 1;</code>
     * @return The homeworkId.
     */
    public java.lang.String getHomeworkId() {
      java.lang.Object ref = homeworkId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        homeworkId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * The id of the Homework to be done
     * </pre>
     *
     * <code>string homework_id = 1;</code>
     * @return The bytes for homeworkId.
     */
    public com.google.protobuf.ByteString
        getHomeworkIdBytes() {
      java.lang.Object ref = homeworkId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        homeworkId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * The id of the Homework to be done
     * </pre>
     *
     * <code>string homework_id = 1;</code>
     * @param value The homeworkId to set.
     * @return This builder for chaining.
     */
    public Builder setHomeworkId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      homeworkId_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The id of the Homework to be done
     * </pre>
     *
     * <code>string homework_id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearHomeworkId() {
      
      homeworkId_ = getDefaultInstance().getHomeworkId();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The id of the Homework to be done
     * </pre>
     *
     * <code>string homework_id = 1;</code>
     * @param value The bytes for homeworkId to set.
     * @return This builder for chaining.
     */
    public Builder setHomeworkIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      homeworkId_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object userId_ = "";
    /**
     * <pre>
     * The id of the User that does the Homework
     * </pre>
     *
     * <code>string user_id = 2;</code>
     * @return The userId.
     */
    public java.lang.String getUserId() {
      java.lang.Object ref = userId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        userId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * The id of the User that does the Homework
     * </pre>
     *
     * <code>string user_id = 2;</code>
     * @return The bytes for userId.
     */
    public com.google.protobuf.ByteString
        getUserIdBytes() {
      java.lang.Object ref = userId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        userId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * The id of the User that does the Homework
     * </pre>
     *
     * <code>string user_id = 2;</code>
     * @param value The userId to set.
     * @return This builder for chaining.
     */
    public Builder setUserId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      userId_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The id of the User that does the Homework
     * </pre>
     *
     * <code>string user_id = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearUserId() {
      
      userId_ = getDefaultInstance().getUserId();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The id of the User that does the Homework
     * </pre>
     *
     * <code>string user_id = 2;</code>
     * @param value The bytes for userId to set.
     * @return This builder for chaining.
     */
    public Builder setUserIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      userId_ = value;
      onChanged();
      return this;
    }

    private java.util.List<proto.homeworks.Answer> answers_ =
      java.util.Collections.emptyList();
    private void ensureAnswersIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        answers_ = new java.util.ArrayList<proto.homeworks.Answer>(answers_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        proto.homeworks.Answer, proto.homeworks.Answer.Builder, proto.homeworks.AnswerOrBuilder> answersBuilder_;

    /**
     * <pre>
     * All the answers to the Homework. The number of answers must be equal to the
     * number of questions. Answer texts may be empty.
     * </pre>
     *
     * <code>repeated .homeworks.Answer answers = 3;</code>
     */
    public java.util.List<proto.homeworks.Answer> getAnswersList() {
      if (answersBuilder_ == null) {
        return java.util.Collections.unmodifiableList(answers_);
      } else {
        return answersBuilder_.getMessageList();
      }
    }
    /**
     * <pre>
     * All the answers to the Homework. The number of answers must be equal to the
     * number of questions. Answer texts may be empty.
     * </pre>
     *
     * <code>repeated .homeworks.Answer answers = 3;</code>
     */
    public int getAnswersCount() {
      if (answersBuilder_ == null) {
        return answers_.size();
      } else {
        return answersBuilder_.getCount();
      }
    }
    /**
     * <pre>
     * All the answers to the Homework. The number of answers must be equal to the
     * number of questions. Answer texts may be empty.
     * </pre>
     *
     * <code>repeated .homeworks.Answer answers = 3;</code>
     */
    public proto.homeworks.Answer getAnswers(int index) {
      if (answersBuilder_ == null) {
        return answers_.get(index);
      } else {
        return answersBuilder_.getMessage(index);
      }
    }
    /**
     * <pre>
     * All the answers to the Homework. The number of answers must be equal to the
     * number of questions. Answer texts may be empty.
     * </pre>
     *
     * <code>repeated .homeworks.Answer answers = 3;</code>
     */
    public Builder setAnswers(
        int index, proto.homeworks.Answer value) {
      if (answersBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureAnswersIsMutable();
        answers_.set(index, value);
        onChanged();
      } else {
        answersBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * All the answers to the Homework. The number of answers must be equal to the
     * number of questions. Answer texts may be empty.
     * </pre>
     *
     * <code>repeated .homeworks.Answer answers = 3;</code>
     */
    public Builder setAnswers(
        int index, proto.homeworks.Answer.Builder builderForValue) {
      if (answersBuilder_ == null) {
        ensureAnswersIsMutable();
        answers_.set(index, builderForValue.build());
        onChanged();
      } else {
        answersBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * All the answers to the Homework. The number of answers must be equal to the
     * number of questions. Answer texts may be empty.
     * </pre>
     *
     * <code>repeated .homeworks.Answer answers = 3;</code>
     */
    public Builder addAnswers(proto.homeworks.Answer value) {
      if (answersBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureAnswersIsMutable();
        answers_.add(value);
        onChanged();
      } else {
        answersBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <pre>
     * All the answers to the Homework. The number of answers must be equal to the
     * number of questions. Answer texts may be empty.
     * </pre>
     *
     * <code>repeated .homeworks.Answer answers = 3;</code>
     */
    public Builder addAnswers(
        int index, proto.homeworks.Answer value) {
      if (answersBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureAnswersIsMutable();
        answers_.add(index, value);
        onChanged();
      } else {
        answersBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * All the answers to the Homework. The number of answers must be equal to the
     * number of questions. Answer texts may be empty.
     * </pre>
     *
     * <code>repeated .homeworks.Answer answers = 3;</code>
     */
    public Builder addAnswers(
        proto.homeworks.Answer.Builder builderForValue) {
      if (answersBuilder_ == null) {
        ensureAnswersIsMutable();
        answers_.add(builderForValue.build());
        onChanged();
      } else {
        answersBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * All the answers to the Homework. The number of answers must be equal to the
     * number of questions. Answer texts may be empty.
     * </pre>
     *
     * <code>repeated .homeworks.Answer answers = 3;</code>
     */
    public Builder addAnswers(
        int index, proto.homeworks.Answer.Builder builderForValue) {
      if (answersBuilder_ == null) {
        ensureAnswersIsMutable();
        answers_.add(index, builderForValue.build());
        onChanged();
      } else {
        answersBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * All the answers to the Homework. The number of answers must be equal to the
     * number of questions. Answer texts may be empty.
     * </pre>
     *
     * <code>repeated .homeworks.Answer answers = 3;</code>
     */
    public Builder addAllAnswers(
        java.lang.Iterable<? extends proto.homeworks.Answer> values) {
      if (answersBuilder_ == null) {
        ensureAnswersIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, answers_);
        onChanged();
      } else {
        answersBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <pre>
     * All the answers to the Homework. The number of answers must be equal to the
     * number of questions. Answer texts may be empty.
     * </pre>
     *
     * <code>repeated .homeworks.Answer answers = 3;</code>
     */
    public Builder clearAnswers() {
      if (answersBuilder_ == null) {
        answers_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        answersBuilder_.clear();
      }
      return this;
    }
    /**
     * <pre>
     * All the answers to the Homework. The number of answers must be equal to the
     * number of questions. Answer texts may be empty.
     * </pre>
     *
     * <code>repeated .homeworks.Answer answers = 3;</code>
     */
    public Builder removeAnswers(int index) {
      if (answersBuilder_ == null) {
        ensureAnswersIsMutable();
        answers_.remove(index);
        onChanged();
      } else {
        answersBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <pre>
     * All the answers to the Homework. The number of answers must be equal to the
     * number of questions. Answer texts may be empty.
     * </pre>
     *
     * <code>repeated .homeworks.Answer answers = 3;</code>
     */
    public proto.homeworks.Answer.Builder getAnswersBuilder(
        int index) {
      return getAnswersFieldBuilder().getBuilder(index);
    }
    /**
     * <pre>
     * All the answers to the Homework. The number of answers must be equal to the
     * number of questions. Answer texts may be empty.
     * </pre>
     *
     * <code>repeated .homeworks.Answer answers = 3;</code>
     */
    public proto.homeworks.AnswerOrBuilder getAnswersOrBuilder(
        int index) {
      if (answersBuilder_ == null) {
        return answers_.get(index);  } else {
        return answersBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <pre>
     * All the answers to the Homework. The number of answers must be equal to the
     * number of questions. Answer texts may be empty.
     * </pre>
     *
     * <code>repeated .homeworks.Answer answers = 3;</code>
     */
    public java.util.List<? extends proto.homeworks.AnswerOrBuilder> 
         getAnswersOrBuilderList() {
      if (answersBuilder_ != null) {
        return answersBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(answers_);
      }
    }
    /**
     * <pre>
     * All the answers to the Homework. The number of answers must be equal to the
     * number of questions. Answer texts may be empty.
     * </pre>
     *
     * <code>repeated .homeworks.Answer answers = 3;</code>
     */
    public proto.homeworks.Answer.Builder addAnswersBuilder() {
      return getAnswersFieldBuilder().addBuilder(
          proto.homeworks.Answer.getDefaultInstance());
    }
    /**
     * <pre>
     * All the answers to the Homework. The number of answers must be equal to the
     * number of questions. Answer texts may be empty.
     * </pre>
     *
     * <code>repeated .homeworks.Answer answers = 3;</code>
     */
    public proto.homeworks.Answer.Builder addAnswersBuilder(
        int index) {
      return getAnswersFieldBuilder().addBuilder(
          index, proto.homeworks.Answer.getDefaultInstance());
    }
    /**
     * <pre>
     * All the answers to the Homework. The number of answers must be equal to the
     * number of questions. Answer texts may be empty.
     * </pre>
     *
     * <code>repeated .homeworks.Answer answers = 3;</code>
     */
    public java.util.List<proto.homeworks.Answer.Builder> 
         getAnswersBuilderList() {
      return getAnswersFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        proto.homeworks.Answer, proto.homeworks.Answer.Builder, proto.homeworks.AnswerOrBuilder> 
        getAnswersFieldBuilder() {
      if (answersBuilder_ == null) {
        answersBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            proto.homeworks.Answer, proto.homeworks.Answer.Builder, proto.homeworks.AnswerOrBuilder>(
                answers_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        answers_ = null;
      }
      return answersBuilder_;
    }

    private boolean completed_ ;
    /**
     * <pre>
     * Whether this Homework is completed or not
     * </pre>
     *
     * <code>bool completed = 4;</code>
     * @return The completed.
     */
    @java.lang.Override
    public boolean getCompleted() {
      return completed_;
    }
    /**
     * <pre>
     * Whether this Homework is completed or not
     * </pre>
     *
     * <code>bool completed = 4;</code>
     * @param value The completed to set.
     * @return This builder for chaining.
     */
    public Builder setCompleted(boolean value) {
      
      completed_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Whether this Homework is completed or not
     * </pre>
     *
     * <code>bool completed = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearCompleted() {
      
      completed_ = false;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:homeworks.DoHomeworkReq)
  }

  // @@protoc_insertion_point(class_scope:homeworks.DoHomeworkReq)
  private static final proto.homeworks.DoHomeworkReq DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new proto.homeworks.DoHomeworkReq();
  }

  public static proto.homeworks.DoHomeworkReq getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<DoHomeworkReq>
      PARSER = new com.google.protobuf.AbstractParser<DoHomeworkReq>() {
    @java.lang.Override
    public DoHomeworkReq parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<DoHomeworkReq> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<DoHomeworkReq> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public proto.homeworks.DoHomeworkReq getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

