// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: homework.proto

package proto.homeworks;

public interface DoHomeworkReqOrBuilder extends
    // @@protoc_insertion_point(interface_extends:homeworks.DoHomeworkReq)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * The id of the Homework to be done
   * </pre>
   *
   * <code>string homework_id = 1;</code>
   * @return The homeworkId.
   */
  java.lang.String getHomeworkId();
  /**
   * <pre>
   * The id of the Homework to be done
   * </pre>
   *
   * <code>string homework_id = 1;</code>
   * @return The bytes for homeworkId.
   */
  com.google.protobuf.ByteString
      getHomeworkIdBytes();

  /**
   * <pre>
   * The id of the User that does the Homework
   * </pre>
   *
   * <code>string user_id = 2;</code>
   * @return The userId.
   */
  java.lang.String getUserId();
  /**
   * <pre>
   * The id of the User that does the Homework
   * </pre>
   *
   * <code>string user_id = 2;</code>
   * @return The bytes for userId.
   */
  com.google.protobuf.ByteString
      getUserIdBytes();

  /**
   * <pre>
   * All the answers to the Homework. The number of answers must be equal to the
   * number of questions. Answer texts may be empty.
   * </pre>
   *
   * <code>repeated .homeworks.Answer answers = 3;</code>
   */
  java.util.List<proto.homeworks.Answer> 
      getAnswersList();
  /**
   * <pre>
   * All the answers to the Homework. The number of answers must be equal to the
   * number of questions. Answer texts may be empty.
   * </pre>
   *
   * <code>repeated .homeworks.Answer answers = 3;</code>
   */
  proto.homeworks.Answer getAnswers(int index);
  /**
   * <pre>
   * All the answers to the Homework. The number of answers must be equal to the
   * number of questions. Answer texts may be empty.
   * </pre>
   *
   * <code>repeated .homeworks.Answer answers = 3;</code>
   */
  int getAnswersCount();
  /**
   * <pre>
   * All the answers to the Homework. The number of answers must be equal to the
   * number of questions. Answer texts may be empty.
   * </pre>
   *
   * <code>repeated .homeworks.Answer answers = 3;</code>
   */
  java.util.List<? extends proto.homeworks.AnswerOrBuilder> 
      getAnswersOrBuilderList();
  /**
   * <pre>
   * All the answers to the Homework. The number of answers must be equal to the
   * number of questions. Answer texts may be empty.
   * </pre>
   *
   * <code>repeated .homeworks.Answer answers = 3;</code>
   */
  proto.homeworks.AnswerOrBuilder getAnswersOrBuilder(
      int index);

  /**
   * <pre>
   * Whether this Homework is completed or not
   * </pre>
   *
   * <code>bool completed = 4;</code>
   * @return The completed.
   */
  boolean getCompleted();
}
