// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: homework.proto

package proto.homeworks;

/**
 * <pre>
 * Homework contains questions and answers. The number of questions must
 * be equal to the number of answers at all times.
 * </pre>
 *
 * Protobuf type {@code homeworks.Homework}
 */
public final class Homework extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:homeworks.Homework)
    HomeworkOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Homework.newBuilder() to construct.
  private Homework(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Homework() {
    id_ = "";
    assignedTo_ = "";
    questions_ = java.util.Collections.emptyList();
    answers_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new Homework();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return proto.homeworks.HomeworkProto.internal_static_homeworks_Homework_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return proto.homeworks.HomeworkProto.internal_static_homeworks_Homework_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            proto.homeworks.Homework.class, proto.homeworks.Homework.Builder.class);
  }

  public static final int ID_FIELD_NUMBER = 1;
  private volatile java.lang.Object id_;
  /**
   * <pre>
   * The unique id of this Homework
   * </pre>
   *
   * <code>string id = 1;</code>
   * @return The id.
   */
  @java.lang.Override
  public java.lang.String getId() {
    java.lang.Object ref = id_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      id_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * The unique id of this Homework
   * </pre>
   *
   * <code>string id = 1;</code>
   * @return The bytes for id.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getIdBytes() {
    java.lang.Object ref = id_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      id_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ASSIGNED_TO_FIELD_NUMBER = 2;
  private volatile java.lang.Object assignedTo_;
  /**
   * <pre>
   * The id of the user that this Homework is assigned to. Cannot be empty.
   * </pre>
   *
   * <code>string assigned_to = 2;</code>
   * @return The assignedTo.
   */
  @java.lang.Override
  public java.lang.String getAssignedTo() {
    java.lang.Object ref = assignedTo_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      assignedTo_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * The id of the user that this Homework is assigned to. Cannot be empty.
   * </pre>
   *
   * <code>string assigned_to = 2;</code>
   * @return The bytes for assignedTo.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getAssignedToBytes() {
    java.lang.Object ref = assignedTo_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      assignedTo_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int QUESTIONS_FIELD_NUMBER = 3;
  private java.util.List<proto.homeworks.Question> questions_;
  /**
   * <code>repeated .homeworks.Question questions = 3;</code>
   */
  @java.lang.Override
  public java.util.List<proto.homeworks.Question> getQuestionsList() {
    return questions_;
  }
  /**
   * <code>repeated .homeworks.Question questions = 3;</code>
   */
  @java.lang.Override
  public java.util.List<? extends proto.homeworks.QuestionOrBuilder> 
      getQuestionsOrBuilderList() {
    return questions_;
  }
  /**
   * <code>repeated .homeworks.Question questions = 3;</code>
   */
  @java.lang.Override
  public int getQuestionsCount() {
    return questions_.size();
  }
  /**
   * <code>repeated .homeworks.Question questions = 3;</code>
   */
  @java.lang.Override
  public proto.homeworks.Question getQuestions(int index) {
    return questions_.get(index);
  }
  /**
   * <code>repeated .homeworks.Question questions = 3;</code>
   */
  @java.lang.Override
  public proto.homeworks.QuestionOrBuilder getQuestionsOrBuilder(
      int index) {
    return questions_.get(index);
  }

  public static final int ANSWERS_FIELD_NUMBER = 4;
  private java.util.List<proto.homeworks.Answer> answers_;
  /**
   * <code>repeated .homeworks.Answer answers = 4;</code>
   */
  @java.lang.Override
  public java.util.List<proto.homeworks.Answer> getAnswersList() {
    return answers_;
  }
  /**
   * <code>repeated .homeworks.Answer answers = 4;</code>
   */
  @java.lang.Override
  public java.util.List<? extends proto.homeworks.AnswerOrBuilder> 
      getAnswersOrBuilderList() {
    return answers_;
  }
  /**
   * <code>repeated .homeworks.Answer answers = 4;</code>
   */
  @java.lang.Override
  public int getAnswersCount() {
    return answers_.size();
  }
  /**
   * <code>repeated .homeworks.Answer answers = 4;</code>
   */
  @java.lang.Override
  public proto.homeworks.Answer getAnswers(int index) {
    return answers_.get(index);
  }
  /**
   * <code>repeated .homeworks.Answer answers = 4;</code>
   */
  @java.lang.Override
  public proto.homeworks.AnswerOrBuilder getAnswersOrBuilder(
      int index) {
    return answers_.get(index);
  }

  public static final int COMPLETED_FIELD_NUMBER = 5;
  private boolean completed_;
  /**
   * <code>bool completed = 5;</code>
   * @return The completed.
   */
  @java.lang.Override
  public boolean getCompleted() {
    return completed_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(id_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, id_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(assignedTo_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, assignedTo_);
    }
    for (int i = 0; i < questions_.size(); i++) {
      output.writeMessage(3, questions_.get(i));
    }
    for (int i = 0; i < answers_.size(); i++) {
      output.writeMessage(4, answers_.get(i));
    }
    if (completed_ != false) {
      output.writeBool(5, completed_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(id_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, id_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(assignedTo_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, assignedTo_);
    }
    for (int i = 0; i < questions_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, questions_.get(i));
    }
    for (int i = 0; i < answers_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, answers_.get(i));
    }
    if (completed_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(5, completed_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof proto.homeworks.Homework)) {
      return super.equals(obj);
    }
    proto.homeworks.Homework other = (proto.homeworks.Homework) obj;

    if (!getId()
        .equals(other.getId())) return false;
    if (!getAssignedTo()
        .equals(other.getAssignedTo())) return false;
    if (!getQuestionsList()
        .equals(other.getQuestionsList())) return false;
    if (!getAnswersList()
        .equals(other.getAnswersList())) return false;
    if (getCompleted()
        != other.getCompleted()) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + ID_FIELD_NUMBER;
    hash = (53 * hash) + getId().hashCode();
    hash = (37 * hash) + ASSIGNED_TO_FIELD_NUMBER;
    hash = (53 * hash) + getAssignedTo().hashCode();
    if (getQuestionsCount() > 0) {
      hash = (37 * hash) + QUESTIONS_FIELD_NUMBER;
      hash = (53 * hash) + getQuestionsList().hashCode();
    }
    if (getAnswersCount() > 0) {
      hash = (37 * hash) + ANSWERS_FIELD_NUMBER;
      hash = (53 * hash) + getAnswersList().hashCode();
    }
    hash = (37 * hash) + COMPLETED_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getCompleted());
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static proto.homeworks.Homework parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static proto.homeworks.Homework parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static proto.homeworks.Homework parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static proto.homeworks.Homework parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static proto.homeworks.Homework parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static proto.homeworks.Homework parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static proto.homeworks.Homework parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static proto.homeworks.Homework parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static proto.homeworks.Homework parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static proto.homeworks.Homework parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static proto.homeworks.Homework parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static proto.homeworks.Homework parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(proto.homeworks.Homework prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * Homework contains questions and answers. The number of questions must
   * be equal to the number of answers at all times.
   * </pre>
   *
   * Protobuf type {@code homeworks.Homework}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:homeworks.Homework)
      proto.homeworks.HomeworkOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return proto.homeworks.HomeworkProto.internal_static_homeworks_Homework_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return proto.homeworks.HomeworkProto.internal_static_homeworks_Homework_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              proto.homeworks.Homework.class, proto.homeworks.Homework.Builder.class);
    }

    // Construct using proto.homeworks.Homework.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      id_ = "";

      assignedTo_ = "";

      if (questionsBuilder_ == null) {
        questions_ = java.util.Collections.emptyList();
      } else {
        questions_ = null;
        questionsBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000001);
      if (answersBuilder_ == null) {
        answers_ = java.util.Collections.emptyList();
      } else {
        answers_ = null;
        answersBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000002);
      completed_ = false;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return proto.homeworks.HomeworkProto.internal_static_homeworks_Homework_descriptor;
    }

    @java.lang.Override
    public proto.homeworks.Homework getDefaultInstanceForType() {
      return proto.homeworks.Homework.getDefaultInstance();
    }

    @java.lang.Override
    public proto.homeworks.Homework build() {
      proto.homeworks.Homework result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public proto.homeworks.Homework buildPartial() {
      proto.homeworks.Homework result = new proto.homeworks.Homework(this);
      int from_bitField0_ = bitField0_;
      result.id_ = id_;
      result.assignedTo_ = assignedTo_;
      if (questionsBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          questions_ = java.util.Collections.unmodifiableList(questions_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.questions_ = questions_;
      } else {
        result.questions_ = questionsBuilder_.build();
      }
      if (answersBuilder_ == null) {
        if (((bitField0_ & 0x00000002) != 0)) {
          answers_ = java.util.Collections.unmodifiableList(answers_);
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.answers_ = answers_;
      } else {
        result.answers_ = answersBuilder_.build();
      }
      result.completed_ = completed_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof proto.homeworks.Homework) {
        return mergeFrom((proto.homeworks.Homework)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(proto.homeworks.Homework other) {
      if (other == proto.homeworks.Homework.getDefaultInstance()) return this;
      if (!other.getId().isEmpty()) {
        id_ = other.id_;
        onChanged();
      }
      if (!other.getAssignedTo().isEmpty()) {
        assignedTo_ = other.assignedTo_;
        onChanged();
      }
      if (questionsBuilder_ == null) {
        if (!other.questions_.isEmpty()) {
          if (questions_.isEmpty()) {
            questions_ = other.questions_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureQuestionsIsMutable();
            questions_.addAll(other.questions_);
          }
          onChanged();
        }
      } else {
        if (!other.questions_.isEmpty()) {
          if (questionsBuilder_.isEmpty()) {
            questionsBuilder_.dispose();
            questionsBuilder_ = null;
            questions_ = other.questions_;
            bitField0_ = (bitField0_ & ~0x00000001);
            questionsBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getQuestionsFieldBuilder() : null;
          } else {
            questionsBuilder_.addAllMessages(other.questions_);
          }
        }
      }
      if (answersBuilder_ == null) {
        if (!other.answers_.isEmpty()) {
          if (answers_.isEmpty()) {
            answers_ = other.answers_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensureAnswersIsMutable();
            answers_.addAll(other.answers_);
          }
          onChanged();
        }
      } else {
        if (!other.answers_.isEmpty()) {
          if (answersBuilder_.isEmpty()) {
            answersBuilder_.dispose();
            answersBuilder_ = null;
            answers_ = other.answers_;
            bitField0_ = (bitField0_ & ~0x00000002);
            answersBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getAnswersFieldBuilder() : null;
          } else {
            answersBuilder_.addAllMessages(other.answers_);
          }
        }
      }
      if (other.getCompleted() != false) {
        setCompleted(other.getCompleted());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              id_ = input.readStringRequireUtf8();

              break;
            } // case 10
            case 18: {
              assignedTo_ = input.readStringRequireUtf8();

              break;
            } // case 18
            case 26: {
              proto.homeworks.Question m =
                  input.readMessage(
                      proto.homeworks.Question.parser(),
                      extensionRegistry);
              if (questionsBuilder_ == null) {
                ensureQuestionsIsMutable();
                questions_.add(m);
              } else {
                questionsBuilder_.addMessage(m);
              }
              break;
            } // case 26
            case 34: {
              proto.homeworks.Answer m =
                  input.readMessage(
                      proto.homeworks.Answer.parser(),
                      extensionRegistry);
              if (answersBuilder_ == null) {
                ensureAnswersIsMutable();
                answers_.add(m);
              } else {
                answersBuilder_.addMessage(m);
              }
              break;
            } // case 34
            case 40: {
              completed_ = input.readBool();

              break;
            } // case 40
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object id_ = "";
    /**
     * <pre>
     * The unique id of this Homework
     * </pre>
     *
     * <code>string id = 1;</code>
     * @return The id.
     */
    public java.lang.String getId() {
      java.lang.Object ref = id_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        id_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * The unique id of this Homework
     * </pre>
     *
     * <code>string id = 1;</code>
     * @return The bytes for id.
     */
    public com.google.protobuf.ByteString
        getIdBytes() {
      java.lang.Object ref = id_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        id_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * The unique id of this Homework
     * </pre>
     *
     * <code>string id = 1;</code>
     * @param value The id to set.
     * @return This builder for chaining.
     */
    public Builder setId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      id_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The unique id of this Homework
     * </pre>
     *
     * <code>string id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearId() {
      
      id_ = getDefaultInstance().getId();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The unique id of this Homework
     * </pre>
     *
     * <code>string id = 1;</code>
     * @param value The bytes for id to set.
     * @return This builder for chaining.
     */
    public Builder setIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      id_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object assignedTo_ = "";
    /**
     * <pre>
     * The id of the user that this Homework is assigned to. Cannot be empty.
     * </pre>
     *
     * <code>string assigned_to = 2;</code>
     * @return The assignedTo.
     */
    public java.lang.String getAssignedTo() {
      java.lang.Object ref = assignedTo_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        assignedTo_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * The id of the user that this Homework is assigned to. Cannot be empty.
     * </pre>
     *
     * <code>string assigned_to = 2;</code>
     * @return The bytes for assignedTo.
     */
    public com.google.protobuf.ByteString
        getAssignedToBytes() {
      java.lang.Object ref = assignedTo_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        assignedTo_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * The id of the user that this Homework is assigned to. Cannot be empty.
     * </pre>
     *
     * <code>string assigned_to = 2;</code>
     * @param value The assignedTo to set.
     * @return This builder for chaining.
     */
    public Builder setAssignedTo(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      assignedTo_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The id of the user that this Homework is assigned to. Cannot be empty.
     * </pre>
     *
     * <code>string assigned_to = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearAssignedTo() {
      
      assignedTo_ = getDefaultInstance().getAssignedTo();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The id of the user that this Homework is assigned to. Cannot be empty.
     * </pre>
     *
     * <code>string assigned_to = 2;</code>
     * @param value The bytes for assignedTo to set.
     * @return This builder for chaining.
     */
    public Builder setAssignedToBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      assignedTo_ = value;
      onChanged();
      return this;
    }

    private java.util.List<proto.homeworks.Question> questions_ =
      java.util.Collections.emptyList();
    private void ensureQuestionsIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        questions_ = new java.util.ArrayList<proto.homeworks.Question>(questions_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        proto.homeworks.Question, proto.homeworks.Question.Builder, proto.homeworks.QuestionOrBuilder> questionsBuilder_;

    /**
     * <code>repeated .homeworks.Question questions = 3;</code>
     */
    public java.util.List<proto.homeworks.Question> getQuestionsList() {
      if (questionsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(questions_);
      } else {
        return questionsBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .homeworks.Question questions = 3;</code>
     */
    public int getQuestionsCount() {
      if (questionsBuilder_ == null) {
        return questions_.size();
      } else {
        return questionsBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .homeworks.Question questions = 3;</code>
     */
    public proto.homeworks.Question getQuestions(int index) {
      if (questionsBuilder_ == null) {
        return questions_.get(index);
      } else {
        return questionsBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .homeworks.Question questions = 3;</code>
     */
    public Builder setQuestions(
        int index, proto.homeworks.Question value) {
      if (questionsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureQuestionsIsMutable();
        questions_.set(index, value);
        onChanged();
      } else {
        questionsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .homeworks.Question questions = 3;</code>
     */
    public Builder setQuestions(
        int index, proto.homeworks.Question.Builder builderForValue) {
      if (questionsBuilder_ == null) {
        ensureQuestionsIsMutable();
        questions_.set(index, builderForValue.build());
        onChanged();
      } else {
        questionsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .homeworks.Question questions = 3;</code>
     */
    public Builder addQuestions(proto.homeworks.Question value) {
      if (questionsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureQuestionsIsMutable();
        questions_.add(value);
        onChanged();
      } else {
        questionsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .homeworks.Question questions = 3;</code>
     */
    public Builder addQuestions(
        int index, proto.homeworks.Question value) {
      if (questionsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureQuestionsIsMutable();
        questions_.add(index, value);
        onChanged();
      } else {
        questionsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .homeworks.Question questions = 3;</code>
     */
    public Builder addQuestions(
        proto.homeworks.Question.Builder builderForValue) {
      if (questionsBuilder_ == null) {
        ensureQuestionsIsMutable();
        questions_.add(builderForValue.build());
        onChanged();
      } else {
        questionsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .homeworks.Question questions = 3;</code>
     */
    public Builder addQuestions(
        int index, proto.homeworks.Question.Builder builderForValue) {
      if (questionsBuilder_ == null) {
        ensureQuestionsIsMutable();
        questions_.add(index, builderForValue.build());
        onChanged();
      } else {
        questionsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .homeworks.Question questions = 3;</code>
     */
    public Builder addAllQuestions(
        java.lang.Iterable<? extends proto.homeworks.Question> values) {
      if (questionsBuilder_ == null) {
        ensureQuestionsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, questions_);
        onChanged();
      } else {
        questionsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .homeworks.Question questions = 3;</code>
     */
    public Builder clearQuestions() {
      if (questionsBuilder_ == null) {
        questions_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        questionsBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .homeworks.Question questions = 3;</code>
     */
    public Builder removeQuestions(int index) {
      if (questionsBuilder_ == null) {
        ensureQuestionsIsMutable();
        questions_.remove(index);
        onChanged();
      } else {
        questionsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .homeworks.Question questions = 3;</code>
     */
    public proto.homeworks.Question.Builder getQuestionsBuilder(
        int index) {
      return getQuestionsFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .homeworks.Question questions = 3;</code>
     */
    public proto.homeworks.QuestionOrBuilder getQuestionsOrBuilder(
        int index) {
      if (questionsBuilder_ == null) {
        return questions_.get(index);  } else {
        return questionsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .homeworks.Question questions = 3;</code>
     */
    public java.util.List<? extends proto.homeworks.QuestionOrBuilder> 
         getQuestionsOrBuilderList() {
      if (questionsBuilder_ != null) {
        return questionsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(questions_);
      }
    }
    /**
     * <code>repeated .homeworks.Question questions = 3;</code>
     */
    public proto.homeworks.Question.Builder addQuestionsBuilder() {
      return getQuestionsFieldBuilder().addBuilder(
          proto.homeworks.Question.getDefaultInstance());
    }
    /**
     * <code>repeated .homeworks.Question questions = 3;</code>
     */
    public proto.homeworks.Question.Builder addQuestionsBuilder(
        int index) {
      return getQuestionsFieldBuilder().addBuilder(
          index, proto.homeworks.Question.getDefaultInstance());
    }
    /**
     * <code>repeated .homeworks.Question questions = 3;</code>
     */
    public java.util.List<proto.homeworks.Question.Builder> 
         getQuestionsBuilderList() {
      return getQuestionsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        proto.homeworks.Question, proto.homeworks.Question.Builder, proto.homeworks.QuestionOrBuilder> 
        getQuestionsFieldBuilder() {
      if (questionsBuilder_ == null) {
        questionsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            proto.homeworks.Question, proto.homeworks.Question.Builder, proto.homeworks.QuestionOrBuilder>(
                questions_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        questions_ = null;
      }
      return questionsBuilder_;
    }

    private java.util.List<proto.homeworks.Answer> answers_ =
      java.util.Collections.emptyList();
    private void ensureAnswersIsMutable() {
      if (!((bitField0_ & 0x00000002) != 0)) {
        answers_ = new java.util.ArrayList<proto.homeworks.Answer>(answers_);
        bitField0_ |= 0x00000002;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        proto.homeworks.Answer, proto.homeworks.Answer.Builder, proto.homeworks.AnswerOrBuilder> answersBuilder_;

    /**
     * <code>repeated .homeworks.Answer answers = 4;</code>
     */
    public java.util.List<proto.homeworks.Answer> getAnswersList() {
      if (answersBuilder_ == null) {
        return java.util.Collections.unmodifiableList(answers_);
      } else {
        return answersBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .homeworks.Answer answers = 4;</code>
     */
    public int getAnswersCount() {
      if (answersBuilder_ == null) {
        return answers_.size();
      } else {
        return answersBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .homeworks.Answer answers = 4;</code>
     */
    public proto.homeworks.Answer getAnswers(int index) {
      if (answersBuilder_ == null) {
        return answers_.get(index);
      } else {
        return answersBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .homeworks.Answer answers = 4;</code>
     */
    public Builder setAnswers(
        int index, proto.homeworks.Answer value) {
      if (answersBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureAnswersIsMutable();
        answers_.set(index, value);
        onChanged();
      } else {
        answersBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .homeworks.Answer answers = 4;</code>
     */
    public Builder setAnswers(
        int index, proto.homeworks.Answer.Builder builderForValue) {
      if (answersBuilder_ == null) {
        ensureAnswersIsMutable();
        answers_.set(index, builderForValue.build());
        onChanged();
      } else {
        answersBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .homeworks.Answer answers = 4;</code>
     */
    public Builder addAnswers(proto.homeworks.Answer value) {
      if (answersBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureAnswersIsMutable();
        answers_.add(value);
        onChanged();
      } else {
        answersBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .homeworks.Answer answers = 4;</code>
     */
    public Builder addAnswers(
        int index, proto.homeworks.Answer value) {
      if (answersBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureAnswersIsMutable();
        answers_.add(index, value);
        onChanged();
      } else {
        answersBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .homeworks.Answer answers = 4;</code>
     */
    public Builder addAnswers(
        proto.homeworks.Answer.Builder builderForValue) {
      if (answersBuilder_ == null) {
        ensureAnswersIsMutable();
        answers_.add(builderForValue.build());
        onChanged();
      } else {
        answersBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .homeworks.Answer answers = 4;</code>
     */
    public Builder addAnswers(
        int index, proto.homeworks.Answer.Builder builderForValue) {
      if (answersBuilder_ == null) {
        ensureAnswersIsMutable();
        answers_.add(index, builderForValue.build());
        onChanged();
      } else {
        answersBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .homeworks.Answer answers = 4;</code>
     */
    public Builder addAllAnswers(
        java.lang.Iterable<? extends proto.homeworks.Answer> values) {
      if (answersBuilder_ == null) {
        ensureAnswersIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, answers_);
        onChanged();
      } else {
        answersBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .homeworks.Answer answers = 4;</code>
     */
    public Builder clearAnswers() {
      if (answersBuilder_ == null) {
        answers_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
      } else {
        answersBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .homeworks.Answer answers = 4;</code>
     */
    public Builder removeAnswers(int index) {
      if (answersBuilder_ == null) {
        ensureAnswersIsMutable();
        answers_.remove(index);
        onChanged();
      } else {
        answersBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .homeworks.Answer answers = 4;</code>
     */
    public proto.homeworks.Answer.Builder getAnswersBuilder(
        int index) {
      return getAnswersFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .homeworks.Answer answers = 4;</code>
     */
    public proto.homeworks.AnswerOrBuilder getAnswersOrBuilder(
        int index) {
      if (answersBuilder_ == null) {
        return answers_.get(index);  } else {
        return answersBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .homeworks.Answer answers = 4;</code>
     */
    public java.util.List<? extends proto.homeworks.AnswerOrBuilder> 
         getAnswersOrBuilderList() {
      if (answersBuilder_ != null) {
        return answersBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(answers_);
      }
    }
    /**
     * <code>repeated .homeworks.Answer answers = 4;</code>
     */
    public proto.homeworks.Answer.Builder addAnswersBuilder() {
      return getAnswersFieldBuilder().addBuilder(
          proto.homeworks.Answer.getDefaultInstance());
    }
    /**
     * <code>repeated .homeworks.Answer answers = 4;</code>
     */
    public proto.homeworks.Answer.Builder addAnswersBuilder(
        int index) {
      return getAnswersFieldBuilder().addBuilder(
          index, proto.homeworks.Answer.getDefaultInstance());
    }
    /**
     * <code>repeated .homeworks.Answer answers = 4;</code>
     */
    public java.util.List<proto.homeworks.Answer.Builder> 
         getAnswersBuilderList() {
      return getAnswersFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        proto.homeworks.Answer, proto.homeworks.Answer.Builder, proto.homeworks.AnswerOrBuilder> 
        getAnswersFieldBuilder() {
      if (answersBuilder_ == null) {
        answersBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            proto.homeworks.Answer, proto.homeworks.Answer.Builder, proto.homeworks.AnswerOrBuilder>(
                answers_,
                ((bitField0_ & 0x00000002) != 0),
                getParentForChildren(),
                isClean());
        answers_ = null;
      }
      return answersBuilder_;
    }

    private boolean completed_ ;
    /**
     * <code>bool completed = 5;</code>
     * @return The completed.
     */
    @java.lang.Override
    public boolean getCompleted() {
      return completed_;
    }
    /**
     * <code>bool completed = 5;</code>
     * @param value The completed to set.
     * @return This builder for chaining.
     */
    public Builder setCompleted(boolean value) {
      
      completed_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bool completed = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearCompleted() {
      
      completed_ = false;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:homeworks.Homework)
  }

  // @@protoc_insertion_point(class_scope:homeworks.Homework)
  private static final proto.homeworks.Homework DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new proto.homeworks.Homework();
  }

  public static proto.homeworks.Homework getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Homework>
      PARSER = new com.google.protobuf.AbstractParser<Homework>() {
    @java.lang.Override
    public Homework parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<Homework> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Homework> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public proto.homeworks.Homework getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

